### ISSUE TITLE
WebSocketApiHttpClientSingleton and WebSocketStreamHttpClientSingleton do not have proxy configurations similar to HttpClientSingleton

### ISSUE THREAD

**Issue by MoneyGuyy** [binance/binance-connector-java#103]
Hello, I found that the HttpClientSingleton used in SpotClient can support manual proxy settings and cancellations. However, WebSocketApiHttpClientSingleton and WebSocketStreamHttpClientSingleton do not provide proxy configurations similar to HttpClientSingleton. What should I do if I want to configure proxies for these two WebSockets

**Comment by aisling-2** [comment]
Hi, this is due to limitations in the underlying library 'OkHttp.' Based on past research, when using WebSocket, there's an incompatibility between how the library's connection is sent (over the SSL layer) and what most proxies accept (over the HTTP layer). We might look for an alternative library in the future; however, including a proxy in WebSockets is not in the short-term plan.

**Comment by MoneyGuyy** [comment]
Okay, it turns out that Okhttp's inventory is restricted. Thank you
